evt_mangmt/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('venue/',include('venue.urls'))
]

venue/urls.py
from django.urls import path
from . import views
app_name='venue'
urlpatterns = [
    path('',views.index,name='def') ,
    path('home',views.home,name='hom'),
    path('room',views.fun,name='rom')

]

venue/models.py
from django.db import models

# Create your models here.

venue/views.py
from django.shortcuts import render

# Create your views here.
def index (request):
    return render(request,'hall.html')

def home (request):
    return render (request,'home.html')

def fun (request):
    return render (request,'room.html')

venue/templates/hall.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>helloooo world</h1>
    <img src="{% static 'images/flower2.jpg' %}">
    <a href="{%url 'venue:hom' %}">world</a>
    <h1>haiiiiiiiiiiii</h1>
</body>
</html>

venue/templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
 <h1>hhhhhhhhhhhhhh</h1>
 <img src="{% static 'images/flower1.jpg' %}" >
 <a href="{% url 'venue:rom'%} ">ind</a>

</body>
</html>

venue/templates/room.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>hi</h1>
</body>
</html>